trigger: none

parameters:
  - name: k8s_environment
    displayName: K8s Environment
    type: string
    values:
      - agrid-01-d1-spoke1-aks-001-admin
      - agrid-01-d1-utility-aks-001-admin
  - name: platform_component
    displayName: Platform Component
    type: string
    default: '---Select Component---'
    values:
    - '---Select Component---'
    - CSIDriver
    - Fluentd
    - IngressController
    - Jaeger
    - Kafka
    - Litmus
    - LitmusAgent
    - Elastic_Kibana
    - Prometheus
    - OAuth2
    - Ambassador
    - Ambassador_Edge_Stack    
  - name: version
    displayName: Version
    default:
    type: string
    values:
    - 1.5.0   
  - name: deployment_type
    displayName: Deployment Type
    type: string
    default: 'Dry-Run'
    values:
    - 'Dry-Run'
    - 'Dry-Run + Deploy'

variables:
  - ${{ if eq(variables['System.TeamFoundationCollectionUri'], 'https://dev.azure.com/SaaSCloudPlatform/') }}:
    - template: ../../common/variables/CD/CUAT/${{ parameters.platform_component }}/${{ parameters.k8s_environment }}.yml
    - template: ../../common/variables/CD/CUAT/CI-CD-Common-vars.yml  
    - name: kube_config
      value: ${{ parameters.k8s_environment }}      
    - name: platform_component  
      value: ${{ parameters.platform_component }}
    - name: deployment_type  
      value: ${{ parameters.deployment_type }}
    - name: helm_chart_version
      value: ${{ parameters.version }}     

name: "$(Date:yyyy-MM-dd)$(Rev:.r) (${{ parameters.k8s_environment }} ${{ parameters.platform_component }} ${{ parameters.version }} ${{ parameters.deployment_type }})"

resources:
  repositories:
  - repository: ADO-Docker-agent
    type: githubenterprise
    endpoint: azcrdgithub
    name: Alpha-Grid-Platform-Engineering/ADO-Docker-agent
  - repository: alpha-eng-utilities
    type: githubenterprise
    endpoint: azcrdgithub
    name: Alpha-Grid-Platform-Engineering/alpha-eng-utilities
  - repository: alpha-application-configs
    type: githubenterprise
    endpoint: azcrdgithub
    name: Alpha-Grid-Platform-Engineering/alpha-application-configs     

stages:
- stage: run_docker_agent
  displayName: Run Docker Agent
  jobs:
    - template: ../../common/jobs/build-run-dockerAgent-job.yml
- stage: Deploy
  displayName: Deploy to K8s Cluster
  jobs:
    - template: ../../common/jobs/generic-CD-job.yaml
- stage: clean_up_job
  condition: always()
  displayName: Clean Up Job
  jobs:
    - template: ../../common/jobs/clean-up-job.yml     
