trigger: none

parameters:
  - name: tenant_id
    type: string
    default: c099-q1-001-config.txt

variables:
  - name: tenant_id
    value: ${{ parameters.tenant_id }}
  - name: acr
    value: cpedracr
  - name: kube_config 
    value: cpe-dr-eus2-aks-poc-001-admin
  - ${{ if eq(variables['System.TeamFoundationCollectionUri'], 'https://dev.azure.com/CloudPlatformEngineering/') }}:
    - name: subscription
      value: crd-eng-hub-Subscription
    - name: keyVault
      value: it-kv-001-int-eastus
  - ${{ if eq(variables['System.TeamFoundationCollectionUri'], 'https://dev.azure.com/SaaSCloudPlatform/') }}:
    - name: subscription
      value: crd-eng-hub-Subscription
    - name: keyVault
      value: it-kv-001-int-eastus   

resources:
  repositories:
  - repository: ADO-Docker-agent
    type: githubenterprise
    endpoint: azcrdgithub
    name: Alpha-Grid-Platform-Engineering/ADO-Docker-agent
  - repository: agrid-tenant-shell
    type: githubenterprise
    endpoint: azcrdgithub
    name: Alpha-Grid-Platform-Engineering/agrid-dr-tenant-shell
  - repository: acn-mtls-pki-setup
    type: githubenterprise
    endpoint: azcrdgithub
    name: Alpha-Grid-Platform-Engineering/acn-mtls-pki-setup
  - repository: acn-akv-aks-integrator
    type: githubenterprise
    endpoint: azcrdgithub
    name: Alpha-Grid-Platform-Engineering/acn-akv-aks-integrator
  - repository: agrid-terraform-akv
    type: githubenterprise
    endpoint: azcrdgithub
    name: Alpha-Grid-Platform-Engineering/agrid-terraform-akv            

stages:
- stage: run_docker_agent
  displayName: Run Docker Agent
  jobs:
    - template: ../common/jobs/build-run-dockerAgent-job.yml

- stage: Read_Config
  displayName: Read Config
  jobs:
    - template: ../common/jobs/read-tetant-shell-config-job.yaml
      parameters:
        configEnv: $[stageDependencies.Read_Config.Select_KeyVault_Job.outputs['select_keyvault.configEnv']]

- stage: Deploy
  displayName: Deploy to K8s Cluster
  jobs:
    - template: ../common/jobs/tenant-shell-onboard-job.yaml
- stage: clean_up_job
  condition: always()
  displayName: Clean Up Job
  jobs:
    - template: ../common/jobs/clean-up-job.yml   
